---
title: "Variable Tables"
format: html
editor: source
---

```{r}

if (exists("startrun")) {
  print(fortunes::fortune())
} else {
  source(here::here("scripts", "startHere.R"))
}
acsdf <- read_csv(here::here('data','processed','etddAreaAcsVars.csv'))

totaldf <- acsdf # do rbind or left join later

varsdf <- read_csv(here::here('data','processed','varsdf.csv'))
```


# By Grant

:::{.panel-tabset}

## EPA

```{r}
epaVars <- varsdf %>% 
  filter(str_detect(grant,'EPA')) %>% 
  select(varName)  %>% 
  distinct() %>% 
  pull()
pctVars <- varsdf %>% 
  filter(str_detect(grant,'EPA'), str_detect(varName,'pct')) %>% 
  select(varName)  %>% 
  distinct() %>% 
  pull()
totaldf %>% 
  select(NAME,any_of(epaVars),geography) %>% 
  rename(
    'place'='NAME'
  ) %>% 
  DT::datatable(
    filter="top"
  ) %>% 
  DT::formatPercentage(
    columns=pctVars
  )
#names()
# rename()
```


## ARC

```{r}
arcVars <- varsdf %>% 
  filter(str_detect(grant,'ARC')) %>% 
  select(varName)  %>% 
  distinct() %>% 
  pull()
pctVars <- varsdf %>% 
  filter(str_detect(grant,'ARC'), str_detect(varName,'pct')) %>% 
  select(varName)  %>% 
  distinct() %>% 
  pull()
totaldf %>% 
  select(NAME,any_of(arcVars),geography) %>% 
  rename(
    'place'='NAME'
  ) %>% 
  DT::datatable(
    filter="top"
  ) %>% 
  DT::formatPercentage(
    columns=pctVars,
    digits=1
  )
```


::::

# By Geography

:::{.panel-tabset}
## State

```{r}

pctVars <- varsdf %>% 
  filter(str_detect(varName,'pct')) %>% 
  select(varName)  %>% 
  distinct() %>% 
  pull()
totaldf %>% 
  filter(geography=='state') %>% 
  rename(
    'place'='NAME'
  ) %>% 
  DT::datatable(
    filter="top"
  ) %>% 
  DT::formatPercentage(
    columns=pctVars,
    digits=1
  )
```


## County

```{r}
pctVars <- varsdf %>% 
  filter(str_detect(varName,'pct')) %>% 
  select(varName)  %>% 
  distinct() %>% 
  pull()
totaldf %>% 
  filter(geography=='county') %>% 
  rename(
    'place'='NAME'
  ) %>% 
  DT::datatable(
    filter="top"
  ) %>% 
  DT::formatPercentage(
    columns=pctVars,
    digits=1
  )
```


## Place

```{r}
pctVars <- varsdf %>% 
  filter(str_detect(varName,'pct')) %>% 
  select(varName)  %>% 
  distinct() %>% 
  pull()
totaldf %>% 
  filter(geography=='place') %>% 
  rename(
    'place'='NAME'
  ) %>% 
  DT::datatable(
    filter="top"
  ) %>% 
  DT::formatPercentage(
    columns=pctVars,
    digits=1
  )
```


::::


# All

```{r}
pctVars <- varsdf %>% 
  filter(str_detect(varName,'pct')) %>% 
  select(varName)  %>% 
  distinct() %>% 
  pull()
totaldf %>% 
  rename(
    'place'='NAME'
  ) %>% 
  DT::datatable(
    filter="top"
  ) %>% 
  DT::formatPercentage(
    columns=pctVars,
    digits=1
  )
```



# Variable Guide

```{r}
varsdf %>% 
  DT::datatable(filter="top")
```

```{r}

```

