ETDDPlaces <-
  c(
    "Clinton",
    "Norris",
    "Oak Ridge",
    "Rocky Top",
    "Alcoa",
    "Maryville",
    "Friendsville",
    "Rockford",
    "Louisville",
    "Townsend",
    "Caryville",
    "Jacksboro",
    "Jellico",
    "La Follette",
    "Cumberland Gap",
    "Harrogate",
    "New Tazewell",
    "Tazewell",
    "Newport",
    "Parrottsville",
    "Bean Station",
    "Rutledge",
    "Blaine",
    "Morristown",
    "Baneberry",
    "Dandridge",
    "Jefferson City",
    "New Market",
    "White Pine",
    "Knoxville",
    "Farragut",
    "Loudon",
    "Lenoir",
    "Greenback",
    "Philadelphia",
    "Madisonville",
    "Sweetwater",
    "Tellico Plains",
    "Vonore",
    "Oakdale",
    "Sunbright",
    "Wartburg",
    "Harriman",
    "Kingston",
    "Rockwood",
    "Oliver Springs",
    "Huntsville",
    "Oneida",
    "Winfield",
    "Gatlinburg",
    "Pigeon Forge",
    "Pittman Center",
    "Sevierville",
    "Luttrell",
    "Maynardville",
    "Plainview"
  )


ETDDCounties <- c(
  "Anderson County, Tennessee",
  "Blount County, Tennessee",
  "Campbell County, Tennessee",
  "Claiborne County, Tennessee",
  "Cocke County, Tennessee",
  "Grainger County, Tennessee",
  "Hamblen County, Tennessee",
  "Jefferson County, Tennessee",
  "Knox County, Tennessee",
  "Loudon County, Tennessee",
  "Monroe County, Tennessee",
  "Morgan County, Tennessee",
  "Roane County, Tennessee",
  "Scott County, Tennessee",
  "Sevier County, Tennessee",
  "Union County, Tennessee"
)

save(ETDDPlaces, ETDDCounties, file = here::here("data", "interim", "CountyPlaceNameLists.rda"))
